[toolchain]
channel = "1.68.2"
components = ["rustfmt", "clippy"]
targets = [
  "mips-unknown-linux-musl",
  "armv5te-unknown-linux-gnueabi",
  "armv7-unknown-linux-gnueabihf",
  "aarch64-unknown-linux-gnu",
]
profile = "default"